- name: 
  hosts: all 
  remote_user: ubuntu
  become: yes 
  tasks:
    - name: update
      apt :
         update_cache: yes
    - name: create
      file:
        path: /home/ubuntu/jenkins_home
        state: directory
        mode:  '0777'
    - name: install opn 
      apt :
        name: openjdk-8-jdk    